### PR TITLE
feat(lvol): add snapshot checksum APIs

### PR DESCRIPTION
**Pull request by DamiaSan**
#### Which issue(s) this PR fixes:

Issue https://github.com/longhorn/longhorn/issues/9709

#### Additional documentation or context

This PR depends on the PR https://github.com/longhorn/spdk/pull/38, so it is still a draft. Will convert to a regular PR when the SPDK PR will be merged.

### CODE REVIEW

**Comment by derekbit** [comment]
@DamiaSan  Ready for review?

**Comment by DamiaSan** [comment]
> @DamiaSan Ready for review?

It depends on SPDK PR https://github.com/longhorn/spdk/pull/38. Otherwise CI build will fail.

**Review by shuo-wu — APPROVED** [review]

**Comment by shuo-wu** [comment]
@DamiaSan It's good to go after updating the vendor.

**Comment by DamiaSan** [comment]
SPDK part has been merged, so now this PR is ready for review and to be merged.

**Review by shuo-wu — APPROVED** [review]

**Pull request merged**
