### PR TITLE
Fix stuck client caused by blocking channel operation and wrong timeout value

### PR DESCRIPTION
**Pull request by derekbit**
longhorn/longhorn#7395

### CODE REVIEW

**Comment by innobead** [comment]
Do you think we should also change the following code? This should avoid adding a response channel of a command to the `responseChans` if it is not handled by the SPDK json-rpc server. 

[/pkg/jsonrpc/client.go#L151-L164](https://github.com/longhorn/go-spdk-helper/blob/82442ab5e85c46fb4d99019136147c08ee1b5373/pkg/jsonrpc/client.go#L151-L164)
```go
func (c *Client) handleSend(msgWrapper *messageWrapper) {
	id := c.idCounter
	c.idCounter++
	c.responseChans[id] = msgWrapper.responseChan

	if err := c.encoder.Encode(NewMessage(id, msgWrapper.method, msgWrapper.params)); err != nil {
		logrus.WithError(err).Errorf("Failed to encode during handleSend")

		// In case of the cached error info of the old encoder fails the following response, it's better to recreate the encoder.
		c.encoder = json.NewEncoder(c.conn)
		c.encoder.SetIndent("", "\t")

	}
}
```
:arrow_down: 
```go
func (c *Client) handleSend(msgWrapper *messageWrapper) {
	if err := c.encoder.Encode(NewMessage(id, msgWrapper.method, msgWrapper.params)); err != nil {
		logrus.WithError(err).Errorf("Failed to encode during handleSend")

		// In case of the cached error info of the old encoder fails the following response, it's better to recreate the encoder.
		c.encoder = json.NewEncoder(c.conn)
		c.encoder.SetIndent("", "\t")
        return
	}
        
    id := c.idCounter
	c.idCounter++
	c.responseChans[id] = msgWrapper.responseChan
}
```

**Comment by innobead** [comment]
We should ensure that there is a response channel so that we can confirm that the write command has been processed.

**Comment by derekbit** [comment]
> Do you think we should also change the following code? This should avoid adding a response channel of a command to the `responseChans` if it is not handled by the SPDK json-rpc server.
> 
> [/pkg/jsonrpc/client.go#L151-L164](https://github.com/longhorn/go-spdk-helper/blob/82442ab5e85c46fb4d99019136147c08ee1b5373/pkg/jsonrpc/client.go#L151-L164)
> 
> ```go
> func (c *Client) handleSend(msgWrapper *messageWrapper) {
> 	id := c.idCounter
> 	c.idCounter++
> 	c.responseChans[id] = msgWrapper.responseChan
> 
> 	if err := c.encoder.Encode(NewMessage(id, msgWrapper.method, msgWrapper.params)); err != nil {
> 		logrus.WithError(err).Errorf("Failed to encode during handleSend")
> 
> 		// In case of the cached error info of the old encoder fails the following response, it's better to recreate the encoder.
> 		c.encoder = json.NewEncoder(c.conn)
> 		c.encoder.SetIndent("", "\t")
> 
> 	}
> }
> ```
> 
> ⬇️
> 
> ```go
> func (c *Client) handleSend(msgWrapper *messageWrapper) {
> 	if err := c.encoder.Encode(NewMessage(id, msgWrapper.method, msgWrapper.params)); err != nil {
> 		logrus.WithError(err).Errorf("Failed to encode during handleSend")
> 
> 		// In case of the cached error info of the old encoder fails the following response, it's better to recreate the encoder.
> 		c.encoder = json.NewEncoder(c.conn)
> 		c.encoder.SetIndent("", "\t")
>         return
> 	}
>         
>     id := c.idCounter
> 	c.idCounter++
> 	c.responseChans[id] = msgWrapper.responseChan
> }
> ```

The change looks good to me.

**Review by innobead — DISMISSED** [review]
LGTM. As per my last time, suggest tackling it together if needed.

**Review by innobead — APPROVED** [review]

**Pull request merged**
