### PR TITLE
Fix GetDevices

### PR DESCRIPTION
**Pull request by derekbit**
The output of "nvme list" command varies in format across different distributions and versions when the verbose option is used.
    
Longhorn/longhorn#5744

### CODE REVIEW

**Comment by derekbit** [comment]
After applying the fix, all volumes on Ubuntu, SLES and RHEL8 with nvme-cli v1.16 can be successfully attached.
cc @shuo-wu @innobead  @chriscchien

**Comment by innobead** [comment]
@derekbit is this PR ready?

**Comment by derekbit** [comment]
I'm doing more tests.

**Comment by derekbit** [comment]
The ticket is ready for review,  thanks. @innobead @shuo-wu

**Review by innobead — APPROVED** [review]

**Pull request merged**
